ALTER TABLE MIASTA MOVE TABLESPACE AGENCJA_NIERUCHOMOSCI;
ALTER TABLE TYPY MOVE TABLESPACE AGENCJA_NIERUCHOMOSCI;
ALTER TABLE SPRZEDAWCY MOVE TABLESPACE AGENCJA_NIERUCHOMOSCI;
ALTER TABLE KLIENCI MOVE TABLESPACE AGENCJA_NIERUCHOMOSCI;
ALTER TABLE POSIADLOSCI MOVE TABLESPACE AGENCJA_NIERUCHOMOSCI;


alter index rebuild;